name = "IsItAGoodIdeaTho"
uuid = "a5dceee0-9146-44d3-b091-de159ff999f4"
authors = ["Daniele <dRain88@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
